"""Project a CLI's documented grammar → the manifest its repo commits.

A CLI's command and flag grammar is its public contract: the thing callers
script against, and the thing that must not change silently. This is the first
generator whose source of record is a *running program* rather than a file — it
invokes the CLI the repo declares, parses the help output, and writes a
structured manifest. A renamed flag or a dropped subcommand then shows up as a
diff naming the command and flag, instead of reaching users as an unannounced
behavior change.

The declaration lives in plugin.yml, next to the `suite.cli` flag that already
says a plugin ships one::

    cli:
      invoke: node dist/cli.js     # or: python -m mytool, dotnet run --project …
      engine: usage-lines          # picks the help-output parser
      manifest: spec/v1/cli.yml    # where the projection lands

``invoke`` keeps shipyard engine-agnostic about *running* the CLI; ``engine``
selects the parser, since every CLI framework formats help differently. Engines
land one at a time as suite plugins need them.

Two properties are worth stating rather than assuming:

* **Help text is a lossy source.** Not every CLI documents every flag it
  accepts, and a parser can only record what is printed. The manifest asserts
  what the CLI *documents* — which is the contract worth freezing, but it is not
  the same claim as what the CLI *accepts*.
* **The manifest is a recording.** It is never hand-edited; each run rewrites it
  wholesale. A CLI whose help the declared engine can't parse fails the
  generator rather than writing a partial manifest, because a manifest missing
  half a command reads exactly like a CLI that dropped half a command.
"""
from __future__ import annotations

import pathlib
import re
import shlex
import subprocess

import yaml

from ._common import block, load_mapping, load_plugin, plugin_root

SCHEMA_URL = "https://chris-peterson.github.io/shipyard/cli-manifest.v1.json"
FORMAT_VERSION = 1

HEADER = (
    "# Generated by `shipyard gen-cli-manifest` — do not edit by hand.\n"
    "# The CLI's documented command and flag grammar, recorded from its own help\n"
    "# output. A diff here is a change to the public contract.\n"
)

# Long enough for a CLI that compiles or loads on startup; short enough that one
# waiting on input fails the build instead of hanging it.
HELP_TIMEOUT_SECONDS = 60


# ---- the usage-lines engine ------------------------------------------------
#
# Parses the `Usage:` block that hand-written CLIs print, where each line is one
# invocation form:
#
#     tack deliverable rm <slug> <tack-id> [--to-link]   (clear the deliverable)
#     └ program  └ command path           └ tokens       └ trailing summary
#
# Bracketing carries the grammar: `<x>` required, `[x]` optional, `x...`
# repeatable, `a|b` alternation, `--flag <arg>` a flag that takes one.

_USAGE_HEADING = re.compile(r"^\s*usage:\s*(.*)$", re.I)

# What a run of two or more spaces is followed by when it's column alignment
# inside the grammar rather than the gap before a summary: a flag, a placeholder,
# or a bracketed group opening on either. A summary starting with a lone dash or
# a bracketed word (`[deprecated] …`) stays a summary.
_GRAMMAR_AFTER_GAP = re.compile(r"^(--?[A-Za-z0-9]|<[^\s>]|\[\s*(--?[A-Za-z0-9]|<))")


def _tokenize(line: str) -> tuple[list[str], str]:
    """Split a usage line into its tokens and its trailing prose.

    Whitespace only separates tokens outside brackets, quotes, and angles, so
    `[--file <path>]` stays one token. A run of two or more spaces ends the
    grammar and starts the summary — the convention every aligned help block
    already follows to set descriptions off from the form they describe. Unless
    what follows the gap is itself grammar: a help block that aligns its columns
    *within* the form would otherwise have the rest of its form read as prose,
    dropping flags from the manifest with nothing failing to say so."""
    tokens: list[str] = []
    depth = 0
    quote = ""
    current = ""
    i = 0
    while i < len(line):
        ch = line[i]
        if quote:
            current += ch
            if ch == quote:
                quote = ""
            i += 1
            continue
        if ch in "\"'":
            quote = ch
            current += ch
            i += 1
            continue
        if ch in "[<":
            depth += 1
        elif ch in "]>":
            depth -= 1
        if ch == " " and depth == 0:
            j = i
            while j < len(line) and line[j] == " ":
                j += 1
            if current:
                tokens.append(current)
                current = ""
            rest = line[j:].strip()
            if j - i >= 2 and not _GRAMMAR_AFTER_GAP.match(rest):
                return tokens, rest
            i = j
            continue
        current += ch
        i += 1
    if current:
        tokens.append(current)
    return tokens, ""


def _split_choices(text: str) -> list[str] | None:
    parts = [p.strip() for p in text.split("|")]
    return parts if len(parts) > 1 and all(parts) else None


def _flag(token: str, *, required: bool, repeatable: bool) -> list[dict]:
    """One flag token → the flag entries it documents. A bracketed alternation
    (`[--merge|--replace]`) is a mutually exclusive group, recorded as one entry
    per flag naming its siblings, so the relation survives a reordering."""
    name, _, arg = token.partition(" ")
    arg = arg.strip().strip("<>").strip("\"'")
    names = [n.strip() for n in name.split("|")]
    if not all(n.startswith("-") for n in names):
        # `[--json|text]` alternates a flag with a literal. Recording the literal
        # as a flag would write a name the schema rejects, and dropping it would
        # lose half the form — so the engine says it can't read this one.
        raise SystemExit(
            "shipyard gen-cli-manifest: the usage-lines engine can't record an "
            f"alternation of a flag and a bare word: `{token}`")
    entries = []
    for n in names:
        entry: dict = {"name": n}
        if arg:
            entry["arg"] = arg
        if required:
            entry["required"] = True
        if repeatable:
            entry["repeatable"] = True
        siblings = [o for o in names if o != n]
        if siblings:
            entry["exclusive_with"] = siblings
        entries.append(entry)
    return entries


def _placeholder(token: str) -> str:
    """`<slug>` → `slug`. A composite placeholder (`<src-slug>/<tack-id>`) keeps
    its brackets: they're what makes the shape of the single argument readable,
    and stripping only the outermost pair would leave a name that reads as a
    typo."""
    inner = token[1:-1]
    return token if "<" in inner or ">" in inner else inner.strip()


def _arg(name: str, *, optional: bool, repeatable: bool) -> dict:
    entry: dict = {"name": name}
    if choices := _split_choices(name):
        entry["choices"] = choices
    if optional:
        entry["optional"] = True
    if repeatable:
        entry["repeatable"] = True
    return entry


def _parse_usage_line(tokens: list[str], summary: str) -> tuple[list[str], dict]:
    """One usage line → its command path and the invocation form it documents.

    The command path is the run of bare words up to the first argument: a path
    segment is never bracketed, so the first `<arg>` or `[opt]` ends it. A flag
    doesn't — `config [--global] set <key>` puts the flag between two segments,
    and the flag is recorded on the leaf usage."""
    path: list[str] = []
    args: list[dict] = []
    flags: list[dict] = []
    bound = set()  # indices already consumed as an unbracketed flag's argument
    for index, token in enumerate(tokens):
        if index in bound:
            continue
        repeatable = token.endswith("...")
        if repeatable:
            token = token[:-3]
        optional = token.startswith("[") and token.endswith("]")
        if optional:
            token = token[1:-1].strip()
            # `[<file>...]` brackets the ellipsis with the placeholder, where
            # `[--link <x>]...` puts it outside. Both say repeatable.
            if token.endswith("..."):
                repeatable = True
                token = token[:-3].strip()
        if token.startswith("-"):
            # An unbracketed flag is written apart from its argument
            # (`--url <url>`), where a bracketed one carries it inside
            # (`[--file <path>]`). Bind the bare placeholder that follows, but
            # only a bare one: `--path [<dir>]` documents a switch and an
            # optional positional, not a flag with an optional argument.
            following = tokens[index + 1] if index + 1 < len(tokens) else ""
            if (not optional and " " not in token
                    and following.startswith("<") and following.endswith(">")):
                token = f"{token} {following}"
                bound.add(index + 1)
            flags += _flag(token, required=not optional, repeatable=repeatable)
        elif token.startswith("<") and token.endswith(">"):
            args.append(_arg(_placeholder(token), optional=optional, repeatable=repeatable))
        elif optional or args:
            # A bare word once an argument has been seen: a value the CLI spells
            # out, not a path segment. `[slug]` is the same argument as
            # `[<slug>]` — some help blocks bracket the placeholder, some don't.
            args.append(_arg(token, optional=optional, repeatable=repeatable))
        else:
            path.append(token)
    usage: dict = {}
    if summary:
        usage["summary"] = summary
    if args:
        usage["args"] = args
    if flags:
        usage["flags"] = flags
    return path, usage


def _node(commands: list[dict], segment: str) -> dict:
    for command in commands:
        if command["name"] == segment:
            return command
    command: dict = {"name": segment}
    if choices := _split_choices(segment):
        command["choices"] = choices
    commands.append(command)
    return command


def _normalize(commands: list[dict]) -> None:
    """Settle each node's shape after the tree is built: drop the empty
    `subcommands` list traversal leaves on every leaf, and restate the keys in
    reading order (what it is, then how you call it, then what's under it)."""
    for command in commands:
        subcommands = command.pop("subcommands", None)
        if subcommands:
            _normalize(subcommands)
        for key in ("choices", "usages"):
            if key in command:
                command[key] = command.pop(key)
        if subcommands:
            command["subcommands"] = subcommands


def parse_usage_lines(text: str) -> dict:
    """`Usage:` block → the manifest body. Raises when the block is absent or
    yields nothing: a CLI this engine can't read is a declaration error, not an
    empty grammar."""
    lines = text.splitlines()
    start = next((i for i, l in enumerate(lines) if _USAGE_HEADING.match(l)), None)
    if start is None:
        raise SystemExit(
            "shipyard gen-cli-manifest: the usage-lines engine found no `Usage:` "
            "heading in the CLI's help output. Check the declared `engine:`.")

    # The heading may carry the first form (`Usage: prog <cmd>`); the rest are
    # the indented lines below it, ending at the next unindented section.
    raw = []
    if inline := _USAGE_HEADING.match(lines[start]).group(1).strip():
        raw.append(inline)
    for line in lines[start + 1:]:
        if not line.strip():
            continue
        if not line[:1].isspace():
            break
        raw.append(line.strip())
    if not raw:
        raise SystemExit(
            "shipyard gen-cli-manifest: the usage-lines engine found a `Usage:` "
            "heading with no usage lines under it.")

    program = raw[0].split()[0]
    manifest_usages: list[dict] = []
    commands: list[dict] = []
    for line in raw:
        tokens, summary = _tokenize(line)
        if tokens[0] != program:
            raise SystemExit(
                "shipyard gen-cli-manifest: the usage-lines engine can't parse "
                f"this line — it doesn't start with `{program}`:\n  {line}")
        path, usage = _parse_usage_line(tokens[1:], summary)
        into = manifest_usages
        if path:
            siblings = commands
            for segment in path:
                command = _node(siblings, segment)
                siblings = command.setdefault("subcommands", [])
            into = command.setdefault("usages", [])
        into.append(usage)
    _normalize(commands)
    return {"name": program, "usages": manifest_usages, "commands": commands}


ENGINES = {"usage-lines": parse_usage_lines}


# ---- invocation ------------------------------------------------------------

def _cli_spec(root: str | pathlib.Path | None) -> dict | None:
    """The `cli:` block, or None for a repo that ships no CLI. Every field is
    load-bearing, so a partial block is an error rather than a default: shipyard
    cannot guess how to run a CLI or where its manifest belongs."""
    from ._aggregate import is_aggregate
    if is_aggregate(root):
        # An aggregator declares plugins.yml and no plugin.yml, so asking
        # load_plugin for its `cli:` block would fail the run rather than skip
        # it. A repo presenting other people's plugins ships no CLI of its own.
        return None
    spec = block(load_plugin(root), "cli", "plugin.yml") or None
    if spec is None:
        return None
    if not isinstance(spec, dict):
        raise SystemExit("shipyard gen-cli-manifest: plugin.yml `cli:` must be a block")
    missing = [k for k in ("invoke", "engine", "manifest") if not spec.get(k)]
    if missing:
        raise SystemExit(
            "shipyard gen-cli-manifest: plugin.yml `cli:` is missing "
            f"{', '.join(missing)}")
    if spec["engine"] not in ENGINES:
        raise SystemExit(
            f"shipyard gen-cli-manifest: unknown engine {spec['engine']!r} "
            f"(known: {', '.join(sorted(ENGINES))})")
    return spec


def run_help(root: str | pathlib.Path | None, invoke: str) -> subprocess.CompletedProcess:
    """Run `<invoke> --help` from the repo root, so a relative `invoke` resolves."""
    argv = shlex.split(invoke) + ["--help"]
    try:
        return subprocess.run(
            argv, cwd=plugin_root(root), capture_output=True, text=True,
            stdin=subprocess.DEVNULL, timeout=HELP_TIMEOUT_SECONDS)
    except FileNotFoundError as exc:
        raise SystemExit(
            f"shipyard gen-cli-manifest: can't run the declared `invoke` "
            f"({invoke!r}): {exc.strerror}") from exc
    except subprocess.TimeoutExpired as exc:
        raise SystemExit(
            f"shipyard gen-cli-manifest: `{invoke} --help` did not finish within "
            f"{HELP_TIMEOUT_SECONDS}s") from exc


def help_output(proc: subprocess.CompletedProcess, invoke: str) -> str:
    """The help text a completed run printed. Help goes to stdout on some CLIs
    and stderr on others, and the exit code is 0 on some and 1 on others; neither
    says whether the text is there, so the text is what's checked."""
    text = proc.stdout if proc.stdout.strip() else proc.stderr
    if not text.strip():
        raise SystemExit(
            f"shipyard gen-cli-manifest: `{invoke} --help` printed nothing "
            f"(exit {proc.returncode})")
    return text


def help_text(root: str | pathlib.Path | None, invoke: str) -> str:
    proc = run_help(root, invoke)
    return help_output(proc, invoke)


def _failed_run_note(proc: subprocess.CompletedProcess, invoke: str) -> str:
    """What to add to a parse failure when the CLI also exited non-zero.

    Since the exit code can't decide whether help was printed, a CLI that never
    started still reaches the engine — with its error message as the "help
    output". The engine then reports an unreadable help format, which is the one
    thing that isn't wrong. So the exit code is reported where it's diagnostic:
    alongside a parse failure, as the likelier explanation of it."""
    if proc.returncode == 0:
        return ""
    stderr = "\n".join(f"    {l}" for l in proc.stderr.strip().splitlines()[:5])
    note = (f"\n`{invoke} --help` also exited {proc.returncode}, so the CLI may "
            "not have run at all.")
    return f"{note} It printed on stderr:\n{stderr}" if stderr else note


def _summary(text: str, program: str) -> str:
    """The CLI's one-line self-description: the first line of help, when it comes
    before the usage block and introduces the program by name."""
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if _USAGE_HEADING.match(line):
            return ""
        m = re.match(rf"{re.escape(program)}\s*(?:—|–|-|:)\s*(.+)", line)
        return m.group(1).strip() if m else line
    return ""


def build(root: str | pathlib.Path | None = None) -> str | None:
    """The manifest the CLI's help currently documents, or None for a repo with
    no `cli:` block — a plugin that ships no CLI has no grammar to freeze."""
    spec = _cli_spec(root)
    if spec is None:
        return None
    proc = run_help(root, spec["invoke"])
    text = help_output(proc, spec["invoke"])
    try:
        body = ENGINES[spec["engine"]](text)
    except SystemExit as exc:
        if note := _failed_run_note(proc, spec["invoke"]):
            raise SystemExit(f"{exc}\n{note}") from exc
        raise
    manifest = {
        "schema": SCHEMA_URL,
        "version": FORMAT_VERSION,
        "name": body["name"],
        "engine": spec["engine"],
    }
    if summary := _summary(text, body["name"]):
        manifest["summary"] = summary
    if body["usages"]:
        manifest["usages"] = body["usages"]
    manifest["commands"] = body["commands"]
    # After `commands`, so the checks below can name what the recording found.
    manifest.update(_presentation(spec, body["commands"]))
    return HEADER + yaml.safe_dump(
        manifest, sort_keys=False, allow_unicode=True, width=10_000)


def _presentation(spec: dict, commands: list[dict]) -> dict:
    """The declared organisation of the reference page, checked against what the
    CLI actually documents.

    Grammar and organisation have different sources and neither can supply the
    other. `--help` knows every command and flag but nothing about which belong
    together, what a worked example looks like, or what a reader needs to know
    before the first one. A person knows all three and cannot be trusted to keep
    a list of commands current — the page this replaces was missing three,
    including a whole `repo` family that shipped a release earlier.

    So the recording stays the authority on *what exists*, `plugin.yml` declares
    *how it reads*, and this function refuses any disagreement between them. A
    command in no group is the failure that matters: it's how a new one goes
    undocumented, and it's the check no hand-written page can perform on itself.
    """
    recorded = [c["name"] for c in commands]
    out: dict = {}

    if lede := spec.get("lede"):
        if not isinstance(lede, str):
            raise SystemExit(
                "shipyard gen-cli-manifest: plugin.yml `cli: lede:` must be text")
        out["lede"] = lede.strip()

    groups = spec.get("groups")
    if groups is not None:
        if not isinstance(groups, list):
            raise SystemExit(
                "shipyard gen-cli-manifest: plugin.yml `cli: groups:` must be a list")
        seen: dict[str, str] = {}
        rendered = []
        for entry in groups:
            if not isinstance(entry, dict) or not entry.get("name"):
                raise SystemExit(
                    "shipyard gen-cli-manifest: each `cli: groups:` entry needs a "
                    f"`name:`, got {entry!r}")
            members = entry.get("commands") or []
            if not isinstance(members, list):
                raise SystemExit(
                    f"shipyard gen-cli-manifest: group {entry['name']!r} `commands:` "
                    "must be a list of command names")
            for name in members:
                if name not in recorded:
                    raise SystemExit(
                        f"shipyard gen-cli-manifest: group {entry['name']!r} lists "
                        f"{name!r}, which the CLI's help doesn't document. The "
                        "recording is the authority on what exists.")
                if name in seen:
                    raise SystemExit(
                        f"shipyard gen-cli-manifest: {name!r} is in both "
                        f"{seen[name]!r} and {entry['name']!r}; a command belongs to "
                        "one group.")
                seen[name] = entry["name"]
            group = {"name": entry["name"], "commands": list(members)}
            if about := entry.get("about"):
                group["about"] = str(about).strip()
            rendered.append(group)

        if ungrouped := [c for c in recorded if c not in seen]:
            raise SystemExit(
                "shipyard gen-cli-manifest: the CLI documents commands that no "
                f"group lists: {', '.join(ungrouped)}. Add them to a `cli: groups:` "
                "entry — an ungrouped command is one the reference page would "
                "silently omit.")
        out["groups"] = rendered

    examples = spec.get("examples")
    if examples is not None:
        if not isinstance(examples, dict):
            raise SystemExit(
                "shipyard gen-cli-manifest: plugin.yml `cli: examples:` must map a "
                "command name to its examples")
        rendered_ex: dict[str, list] = {}
        for name, items in examples.items():
            if name not in recorded:
                raise SystemExit(
                    f"shipyard gen-cli-manifest: `cli: examples:` names {name!r}, "
                    "which the CLI's help doesn't document")
            if not isinstance(items, list) or not items:
                raise SystemExit(
                    f"shipyard gen-cli-manifest: examples for {name!r} must be a "
                    "non-empty list")
            built = []
            for item in items:
                if not isinstance(item, dict) or not item.get("run"):
                    raise SystemExit(
                        f"shipyard gen-cli-manifest: each example for {name!r} needs "
                        f"a `run:`, got {item!r}")
                example = {"run": str(item["run"]).strip()}
                if note := item.get("note"):
                    example["note"] = str(note).strip()
                if out_text := item.get("out"):
                    example["out"] = str(out_text).rstrip()
                built.append(example)
            rendered_ex[name] = built
        out["examples"] = rendered_ex

    return out


def target(root: str | pathlib.Path | None = None) -> pathlib.Path | None:
    spec = _cli_spec(root)
    return None if spec is None else plugin_root(root) / spec["manifest"]


def run(root: str | pathlib.Path | None = None) -> int:
    generated = build(root)
    if generated is None:
        return 0
    path = target(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generated)
    return 0


# ---- the reference page ----------------------------------------------------
#
# Rendered from the *committed* manifest, not from a fresh invocation: a docs
# build shouldn't need the CLI built, and the page should show the grammar the
# repo has committed to. Held here rather than in build_docs because rendering a
# usage line is the inverse of parsing one, and the two drift apart if they live
# in different modules.

DOCS_PAGE = "cli.md"


def _render_arg(arg: dict) -> str:
    name = arg["name"]
    # A composite placeholder (`<src-slug>/<tack-id>`) already carries its own
    # brackets — wrapping it again would invent a placeholder that isn't there.
    text = name if name.startswith("<") else f"<{name}>"
    # Inside the brackets, matching how a help block writes a repeatable optional
    # positional (`[<file>...]`). A repeatable *flag* group brackets the other way
    # round (`[--link <x>]...`), so each is rendered the way it's written.
    if arg.get("repeatable"):
        text += "..."
    return f"[{text}]" if arg.get("optional") else text


def _render_flags(flags: list[dict], *, required: bool) -> list[str]:
    rendered: list[str] = []
    done: set[str] = set()
    for flag in flags:
        if flag["name"] in done or bool(flag.get("required")) is not required:
            continue
        group = [flag["name"], *flag.get("exclusive_with", [])]
        done.update(group)
        text = "|".join(group)
        if arg := flag.get("arg"):
            text = f"{text} <{arg}>"
        if not required:
            text = f"[{text}]"
        rendered.append(text + "..." if flag.get("repeatable") else text)
    return rendered


def _render_usage(program: str, path: list[str], usage: dict) -> str:
    """A usage line, rebuilt from what the manifest records.

    The manifest records which tokens are required, not the order the help author
    typed them in, so the line is rebuilt in a canonical one: what you must pass
    before what you may, positionals before flags within each. That happens to
    reproduce the source line for the usual shapes, and reads better than the
    source for the ones where it doesn't — a required `--path` renders ahead of
    an optional `[<dir>]` rather than behind it."""
    # `or []` throughout the renderer: a key present with no value is YAML's
    # null, which means the same as the key being absent. The generator never
    # writes one, but the committed manifest it reads back has been through a
    # human's editor and a merge.
    args = usage.get("args") or []
    flags = usage.get("flags") or []
    return " ".join([
        program, *path,
        *[_render_arg(a) for a in args if not a.get("optional")],
        *_render_flags(flags, required=True),
        *[_render_arg(a) for a in args if a.get("optional")],
        *_render_flags(flags, required=False),
    ])


def _render_command(program: str, command: dict, path: list[str], out: list[str]) -> None:
    here = [*path, command["name"]]
    for usage in command.get("usages") or []:
        out.append(_render_usage(program, here, usage))
        if summary := usage.get("summary"):
            out.append(f"    {summary}")
    for sub in command.get("subcommands") or []:
        _render_command(program, sub, here, out)


def _render_entry(program: str, command: dict, examples: dict, depth: int) -> list[str]:
    forms: list[str] = []
    _render_command(program, command, [], forms)
    lines = [f"{'#' * depth} `{program} {command['name']}`", "",
             "```text", *forms, "```", ""]
    for example in examples.get(command["name"], []):
        if note := example.get("note"):
            lines += [note, ""]
        lines += ["```bash", example["run"], "```", ""]
        if out := example.get("out"):
            lines += ["```text", out, "```", ""]
    return lines


def render_markdown(manifest: dict, source: str) -> str:
    """The manifest as a command reference page. `source` names the manifest the
    page was rendered from, so a reader who spots something wrong knows the page
    is a projection and where the truth lives.

    Grouping, the lede, and the examples are the declared half of the manifest —
    they come from `plugin.yml`, because help output has no way to express them.
    Without them the page is a flat alphabet of commands, which is complete and
    unreadable; with them it's the page a person would have written, except that
    it can't omit a command or drift from the binary."""
    program = manifest["name"]
    groups = manifest.get("groups") or []
    examples = manifest.get("examples") or {}

    lines = [f"# {program}", ""]
    if summary := manifest.get("summary"):
        lines += [summary, ""]
    lines += [
        f"<!-- Generated by shipyard from {source} — do not edit by hand. -->",
        "",
    ]
    if lede := manifest.get("lede"):
        lines += [lede, ""]
    lines += [
        f"Every command `{program}` documents in its own help output. It records "
        "what the CLI documents, which is not necessarily everything it accepts.",
        "",
    ]
    for usage in manifest.get("usages") or []:
        lines += ["```text", _render_usage(program, [], usage), "```", ""]

    commands = {c["name"]: c for c in manifest.get("commands") or []}
    if not groups:
        for command in commands.values():
            lines += _render_entry(program, command, examples, depth=2)
        return "\n".join(lines)

    # Grouped: `##` per group so a sidebar can link a section, `###` per command
    # beneath it. The generator has already refused any group naming a command
    # the recording doesn't have, and any recorded command no group lists, so
    # this walk covers every command exactly once without checking again.
    for group in groups:
        lines += [f"## {group['name']}", ""]
        if about := group.get("about"):
            lines += [about, ""]
        for name in group["commands"]:
            lines += _render_entry(program, commands[name], examples, depth=3)
    return "\n".join(lines)


def docs_page(root: str | pathlib.Path | None = None) -> str | None:
    """The reference page for the committed manifest, or None when the repo
    declares no CLI. A declared manifest that hasn't been generated yet is not an
    error here — the page appears once `generate` has written it."""
    path = target(root)
    if path is None or not path.exists():
        return None
    manifest = load_mapping(path, "a mapping carrying the recorded grammar")
    source = path.relative_to(plugin_root(root)).as_posix()
    if not manifest.get("name"):
        # build-docs gates the release, so an unreadable manifest has to name
        # itself here rather than reaching the renderer and surfacing as a
        # KeyError from inside the docs build.
        raise SystemExit(
            f"shipyard: {source} carries no `name`, so it isn't a CLI manifest. "
            "Re-record it with `shipyard gen-cli-manifest`.")
    return render_markdown(manifest, source)
