"""Project a CLI's documented grammar → the manifest its repo commits.

A CLI's command and flag grammar is its public contract: the thing callers
script against, and the thing that must not change silently. This is the first
generator whose source of record is a *running program* rather than a file — it
invokes the CLI the repo declares, parses the help output, and writes a
structured manifest. A renamed flag or a dropped subcommand then shows up as a
diff naming the command and flag, instead of reaching users as an unannounced
behavior change.

The declaration lives in plugin.yml, next to the `suite.cli` flag that already
says a plugin ships one::

    cli:
      invoke: node dist/cli.js     # or: python -m mytool, dotnet run --project …
      engine: usage-lines          # picks the help-output parser
      manifest: spec/v1/cli.yml    # where the projection lands

``invoke`` keeps shipyard engine-agnostic about *running* the CLI; ``engine``
selects the parser, since every CLI framework formats help differently. Engines
land one at a time as suite plugins need them.

Two properties are worth stating rather than assuming:

* **Help text is a lossy source.** Not every CLI documents every flag it
  accepts, and a parser can only record what is printed. The manifest asserts
  what the CLI *documents* — which is the contract worth freezing, but it is not
  the same claim as what the CLI *accepts*.
* **The manifest is a recording.** It is never hand-edited; each run rewrites it
  wholesale. A CLI whose help the declared engine can't parse fails the
  generator rather than writing a partial manifest, because a manifest missing
  half a command reads exactly like a CLI that dropped half a command.
"""
from __future__ import annotations

import pathlib
import re
import shlex
import subprocess

import yaml

from ._common import diff, load_plugin, plugin_root

SCHEMA_URL = "https://chris-peterson.github.io/shipyard/cli-manifest.v1.json"
FORMAT_VERSION = 1

HEADER = (
    "# Generated by `shipyard gen-cli-manifest` — do not edit by hand.\n"
    "# The CLI's documented command and flag grammar, recorded from its own help\n"
    "# output. A diff here is a change to the public contract.\n"
)

# Long enough for a CLI that compiles or loads on startup; short enough that one
# waiting on input fails the build instead of hanging it.
HELP_TIMEOUT_SECONDS = 60


# ---- the usage-lines engine ------------------------------------------------
#
# Parses the `Usage:` block that hand-written CLIs print, where each line is one
# invocation form:
#
#     tack deliverable rm <slug> <tack-id> [--to-link]   (clear the deliverable)
#     └ program  └ command path           └ tokens       └ trailing summary
#
# Bracketing carries the grammar: `<x>` required, `[x]` optional, `x...`
# repeatable, `a|b` alternation, `--flag <arg>` a flag that takes one.

_USAGE_HEADING = re.compile(r"^\s*usage:\s*(.*)$", re.I)

# What a run of two or more spaces is followed by when it's column alignment
# inside the grammar rather than the gap before a summary: a flag, a placeholder,
# or a bracketed group opening on either. A summary starting with a lone dash or
# a bracketed word (`[deprecated] …`) stays a summary.
_GRAMMAR_AFTER_GAP = re.compile(r"^(--?[A-Za-z0-9]|<[^\s>]|\[\s*(--?[A-Za-z0-9]|<))")


def _tokenize(line: str) -> tuple[list[str], str]:
    """Split a usage line into its tokens and its trailing prose.

    Whitespace only separates tokens outside brackets, quotes, and angles, so
    `[--file <path>]` stays one token. A run of two or more spaces ends the
    grammar and starts the summary — the convention every aligned help block
    already follows to set descriptions off from the form they describe. Unless
    what follows the gap is itself grammar: a help block that aligns its columns
    *within* the form would otherwise have the rest of its form read as prose,
    dropping flags from the manifest with nothing failing to say so."""
    tokens: list[str] = []
    depth = 0
    quote = ""
    current = ""
    i = 0
    while i < len(line):
        ch = line[i]
        if quote:
            current += ch
            if ch == quote:
                quote = ""
            i += 1
            continue
        if ch in "\"'":
            quote = ch
            current += ch
            i += 1
            continue
        if ch in "[<":
            depth += 1
        elif ch in "]>":
            depth -= 1
        if ch == " " and depth == 0:
            j = i
            while j < len(line) and line[j] == " ":
                j += 1
            if current:
                tokens.append(current)
                current = ""
            rest = line[j:].strip()
            if j - i >= 2 and not _GRAMMAR_AFTER_GAP.match(rest):
                return tokens, rest
            i = j
            continue
        current += ch
        i += 1
    if current:
        tokens.append(current)
    return tokens, ""


def _split_choices(text: str) -> list[str] | None:
    parts = [p.strip() for p in text.split("|")]
    return parts if len(parts) > 1 and all(parts) else None


def _flag(token: str, *, required: bool, repeatable: bool) -> list[dict]:
    """One flag token → the flag entries it documents. A bracketed alternation
    (`[--merge|--replace]`) is a mutually exclusive group, recorded as one entry
    per flag naming its siblings, so the relation survives a reordering."""
    name, _, arg = token.partition(" ")
    arg = arg.strip().strip("<>").strip("\"'")
    names = [n.strip() for n in name.split("|")]
    if not all(n.startswith("-") for n in names):
        # `[--json|text]` alternates a flag with a literal. Recording the literal
        # as a flag would write a name the schema rejects, and dropping it would
        # lose half the form — so the engine says it can't read this one.
        raise SystemExit(
            "shipyard gen-cli-manifest: the usage-lines engine can't record an "
            f"alternation of a flag and a bare word: `{token}`")
    entries = []
    for n in names:
        entry: dict = {"name": n}
        if arg:
            entry["arg"] = arg
        if required:
            entry["required"] = True
        if repeatable:
            entry["repeatable"] = True
        siblings = [o for o in names if o != n]
        if siblings:
            entry["exclusive_with"] = siblings
        entries.append(entry)
    return entries


def _placeholder(token: str) -> str:
    """`<slug>` → `slug`. A composite placeholder (`<src-slug>/<tack-id>`) keeps
    its brackets: they're what makes the shape of the single argument readable,
    and stripping only the outermost pair would leave a name that reads as a
    typo."""
    inner = token[1:-1]
    return token if "<" in inner or ">" in inner else inner.strip()


def _arg(name: str, *, optional: bool, repeatable: bool) -> dict:
    entry: dict = {"name": name}
    if choices := _split_choices(name):
        entry["choices"] = choices
    if optional:
        entry["optional"] = True
    if repeatable:
        entry["repeatable"] = True
    return entry


def _parse_usage_line(tokens: list[str], summary: str) -> tuple[list[str], dict]:
    """One usage line → its command path and the invocation form it documents.

    The command path is the run of bare words up to the first argument: a path
    segment is never bracketed, so the first `<arg>` or `[opt]` ends it. A flag
    doesn't — `config [--global] set <key>` puts the flag between two segments,
    and the flag is recorded on the leaf usage."""
    path: list[str] = []
    args: list[dict] = []
    flags: list[dict] = []
    bound = set()  # indices already consumed as an unbracketed flag's argument
    for index, token in enumerate(tokens):
        if index in bound:
            continue
        repeatable = token.endswith("...")
        if repeatable:
            token = token[:-3]
        optional = token.startswith("[") and token.endswith("]")
        if optional:
            token = token[1:-1].strip()
            # `[<file>...]` brackets the ellipsis with the placeholder, where
            # `[--link <x>]...` puts it outside. Both say repeatable.
            if token.endswith("..."):
                repeatable = True
                token = token[:-3].strip()
        if token.startswith("-"):
            # An unbracketed flag is written apart from its argument
            # (`--url <url>`), where a bracketed one carries it inside
            # (`[--file <path>]`). Bind the bare placeholder that follows, but
            # only a bare one: `--path [<dir>]` documents a switch and an
            # optional positional, not a flag with an optional argument.
            following = tokens[index + 1] if index + 1 < len(tokens) else ""
            if (not optional and " " not in token
                    and following.startswith("<") and following.endswith(">")):
                token = f"{token} {following}"
                bound.add(index + 1)
            flags += _flag(token, required=not optional, repeatable=repeatable)
        elif token.startswith("<") and token.endswith(">"):
            args.append(_arg(_placeholder(token), optional=optional, repeatable=repeatable))
        elif optional or args:
            # A bare word once an argument has been seen: a value the CLI spells
            # out, not a path segment. `[slug]` is the same argument as
            # `[<slug>]` — some help blocks bracket the placeholder, some don't.
            args.append(_arg(token, optional=optional, repeatable=repeatable))
        else:
            path.append(token)
    usage: dict = {}
    if summary:
        usage["summary"] = summary
    if args:
        usage["args"] = args
    if flags:
        usage["flags"] = flags
    return path, usage


def _node(commands: list[dict], segment: str) -> dict:
    for command in commands:
        if command["name"] == segment:
            return command
    command: dict = {"name": segment}
    if choices := _split_choices(segment):
        command["choices"] = choices
    commands.append(command)
    return command


def _normalize(commands: list[dict]) -> None:
    """Settle each node's shape after the tree is built: drop the empty
    `subcommands` list traversal leaves on every leaf, and restate the keys in
    reading order (what it is, then how you call it, then what's under it)."""
    for command in commands:
        subcommands = command.pop("subcommands", None)
        if subcommands:
            _normalize(subcommands)
        for key in ("choices", "usages"):
            if key in command:
                command[key] = command.pop(key)
        if subcommands:
            command["subcommands"] = subcommands


def parse_usage_lines(text: str) -> dict:
    """`Usage:` block → the manifest body. Raises when the block is absent or
    yields nothing: a CLI this engine can't read is a declaration error, not an
    empty grammar."""
    lines = text.splitlines()
    start = next((i for i, l in enumerate(lines) if _USAGE_HEADING.match(l)), None)
    if start is None:
        raise SystemExit(
            "shipyard gen-cli-manifest: the usage-lines engine found no `Usage:` "
            "heading in the CLI's help output. Check the declared `engine:`.")

    # The heading may carry the first form (`Usage: prog <cmd>`); the rest are
    # the indented lines below it, ending at the next unindented section.
    raw = []
    if inline := _USAGE_HEADING.match(lines[start]).group(1).strip():
        raw.append(inline)
    for line in lines[start + 1:]:
        if not line.strip():
            continue
        if not line[:1].isspace():
            break
        raw.append(line.strip())
    if not raw:
        raise SystemExit(
            "shipyard gen-cli-manifest: the usage-lines engine found a `Usage:` "
            "heading with no usage lines under it.")

    program = raw[0].split()[0]
    manifest_usages: list[dict] = []
    commands: list[dict] = []
    for line in raw:
        tokens, summary = _tokenize(line)
        if tokens[0] != program:
            raise SystemExit(
                "shipyard gen-cli-manifest: the usage-lines engine can't parse "
                f"this line — it doesn't start with `{program}`:\n  {line}")
        path, usage = _parse_usage_line(tokens[1:], summary)
        into = manifest_usages
        if path:
            siblings = commands
            for segment in path:
                command = _node(siblings, segment)
                siblings = command.setdefault("subcommands", [])
            into = command.setdefault("usages", [])
        into.append(usage)
    _normalize(commands)
    return {"name": program, "usages": manifest_usages, "commands": commands}


ENGINES = {"usage-lines": parse_usage_lines}


# ---- invocation ------------------------------------------------------------

def _cli_spec(root: str | pathlib.Path | None) -> dict | None:
    """The `cli:` block, or None for a repo that ships no CLI. Every field is
    load-bearing, so a partial block is an error rather than a default: shipyard
    cannot guess how to run a CLI or where its manifest belongs."""
    from ._aggregate import is_aggregate
    if is_aggregate(root):
        # An aggregator declares plugins.yml and no plugin.yml, so asking
        # load_plugin for its `cli:` block would fail the run rather than skip
        # it. A repo presenting other people's plugins ships no CLI of its own.
        return None
    spec = load_plugin(root).get("cli")
    if spec is None:
        return None
    if not isinstance(spec, dict):
        raise SystemExit("shipyard gen-cli-manifest: plugin.yml `cli:` must be a block")
    missing = [k for k in ("invoke", "engine", "manifest") if not spec.get(k)]
    if missing:
        raise SystemExit(
            "shipyard gen-cli-manifest: plugin.yml `cli:` is missing "
            f"{', '.join(missing)}")
    if spec["engine"] not in ENGINES:
        raise SystemExit(
            f"shipyard gen-cli-manifest: unknown engine {spec['engine']!r} "
            f"(known: {', '.join(sorted(ENGINES))})")
    return spec


def run_help(root: str | pathlib.Path | None, invoke: str) -> subprocess.CompletedProcess:
    """Run `<invoke> --help` from the repo root, so a relative `invoke` resolves."""
    argv = shlex.split(invoke) + ["--help"]
    try:
        return subprocess.run(
            argv, cwd=plugin_root(root), capture_output=True, text=True,
            stdin=subprocess.DEVNULL, timeout=HELP_TIMEOUT_SECONDS)
    except FileNotFoundError as exc:
        raise SystemExit(
            f"shipyard gen-cli-manifest: can't run the declared `invoke` "
            f"({invoke!r}): {exc.strerror}") from exc
    except subprocess.TimeoutExpired as exc:
        raise SystemExit(
            f"shipyard gen-cli-manifest: `{invoke} --help` did not finish within "
            f"{HELP_TIMEOUT_SECONDS}s") from exc


def help_output(proc: subprocess.CompletedProcess, invoke: str) -> str:
    """The help text a completed run printed. Help goes to stdout on some CLIs
    and stderr on others, and the exit code is 0 on some and 1 on others; neither
    says whether the text is there, so the text is what's checked."""
    text = proc.stdout if proc.stdout.strip() else proc.stderr
    if not text.strip():
        raise SystemExit(
            f"shipyard gen-cli-manifest: `{invoke} --help` printed nothing "
            f"(exit {proc.returncode})")
    return text


def help_text(root: str | pathlib.Path | None, invoke: str) -> str:
    proc = run_help(root, invoke)
    return help_output(proc, invoke)


def _failed_run_note(proc: subprocess.CompletedProcess, invoke: str) -> str:
    """What to add to a parse failure when the CLI also exited non-zero.

    Since the exit code can't decide whether help was printed, a CLI that never
    started still reaches the engine — with its error message as the "help
    output". The engine then reports an unreadable help format, which is the one
    thing that isn't wrong. So the exit code is reported where it's diagnostic:
    alongside a parse failure, as the likelier explanation of it."""
    if proc.returncode == 0:
        return ""
    stderr = "\n".join(f"    {l}" for l in proc.stderr.strip().splitlines()[:5])
    note = (f"\n`{invoke} --help` also exited {proc.returncode}, so the CLI may "
            "not have run at all.")
    return f"{note} It printed on stderr:\n{stderr}" if stderr else note


def _summary(text: str, program: str) -> str:
    """The CLI's one-line self-description: the first line of help, when it comes
    before the usage block and introduces the program by name."""
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if _USAGE_HEADING.match(line):
            return ""
        m = re.match(rf"{re.escape(program)}\s*(?:—|–|-|:)\s*(.+)", line)
        return m.group(1).strip() if m else line
    return ""


def build(root: str | pathlib.Path | None = None) -> str | None:
    """The manifest the CLI's help currently documents, or None for a repo with
    no `cli:` block — a plugin that ships no CLI has no grammar to freeze."""
    spec = _cli_spec(root)
    if spec is None:
        return None
    proc = run_help(root, spec["invoke"])
    text = help_output(proc, spec["invoke"])
    try:
        body = ENGINES[spec["engine"]](text)
    except SystemExit as exc:
        if note := _failed_run_note(proc, spec["invoke"]):
            raise SystemExit(f"{exc}\n{note}") from exc
        raise
    manifest = {
        "schema": SCHEMA_URL,
        "version": FORMAT_VERSION,
        "name": body["name"],
        "engine": spec["engine"],
    }
    if summary := _summary(text, body["name"]):
        manifest["summary"] = summary
    if body["usages"]:
        manifest["usages"] = body["usages"]
    manifest["commands"] = body["commands"]
    return HEADER + yaml.safe_dump(
        manifest, sort_keys=False, allow_unicode=True, width=10_000)


def target(root: str | pathlib.Path | None = None) -> pathlib.Path | None:
    spec = _cli_spec(root)
    return None if spec is None else plugin_root(root) / spec["manifest"]


def _forms(manifest: dict) -> list[str]:
    """Every invocation form the manifest documents, as a usage line. A form
    carries its whole command path, so a set difference over these localizes a
    change the way a YAML diff can't: `--to-link` vanishing shows up as the
    `deliverable rm` line that lost it, not as an unattributed removed line
    several levels below the command it belongs to."""
    program = manifest.get("name", "")
    lines = [_render_usage(program, [], u) for u in manifest.get("usages") or []]
    for command in manifest.get("commands") or []:
        _render_command(program, command, [], lines)
    return [l for l in lines if not l.startswith(" ")]


def check(root: str | pathlib.Path | None = None) -> int:
    """Fail when the committed manifest no longer matches the CLI. Unlike the
    release-committed artifacts — which are expected to trail their source
    between releases — the grammar is the contract under review, so its drift
    belongs in the PR that caused it."""
    generated = build(root)
    if generated is None:
        return 0
    path = target(root)
    current = path.read_text() if path.exists() else ""
    if current == generated:
        return 0

    was = _forms(yaml.safe_load(current) or {}) if current else []
    now = _forms(yaml.safe_load(generated))
    gone = [f for f in was if f not in now]
    added = [f for f in now if f not in was]
    if gone or added:
        print("shipyard: the CLI's grammar has changed and the committed "
              "manifest hasn't.\n")
        for form in gone:
            print(f"  - {form}")
        for form in added:
            print(f"  + {form}")
        print(f"\n{diff(path, current, generated, root)}")
        print("Re-record it with `shipyard gen-cli-manifest`, and review the "
              "diff — it is a change to the CLI's public contract.")
        return 1
    # Every invocation form still matches, so whatever moved is a summary, an
    # ordering, or shipyard's own framing of the file. Saying "the grammar has
    # changed" here would send a reader hunting for a contract change that the
    # empty form list has already ruled out.
    print("shipyard: the committed CLI manifest is out of date, though every "
          "invocation form it documents is unchanged.\n")
    print(f"{diff(path, current, generated, root)}")
    print("Re-record it with `shipyard gen-cli-manifest`.")
    return 1


def run(root: str | pathlib.Path | None = None) -> int:
    generated = build(root)
    if generated is None:
        return 0
    path = target(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generated)
    return 0


# ---- the reference page ----------------------------------------------------
#
# Rendered from the *committed* manifest, not from a fresh invocation: a docs
# build shouldn't need the CLI built, and the page should show the grammar the
# repo has committed to. Held here rather than in build_docs because rendering a
# usage line is the inverse of parsing one, and the two drift apart if they live
# in different modules.

DOCS_PAGE = "cli.md"


def _render_arg(arg: dict) -> str:
    name = arg["name"]
    # A composite placeholder (`<src-slug>/<tack-id>`) already carries its own
    # brackets — wrapping it again would invent a placeholder that isn't there.
    text = name if name.startswith("<") else f"<{name}>"
    # Inside the brackets, matching how a help block writes a repeatable optional
    # positional (`[<file>...]`). A repeatable *flag* group brackets the other way
    # round (`[--link <x>]...`), so each is rendered the way it's written.
    if arg.get("repeatable"):
        text += "..."
    return f"[{text}]" if arg.get("optional") else text


def _render_flags(flags: list[dict], *, required: bool) -> list[str]:
    rendered: list[str] = []
    done: set[str] = set()
    for flag in flags:
        if flag["name"] in done or bool(flag.get("required")) is not required:
            continue
        group = [flag["name"], *flag.get("exclusive_with", [])]
        done.update(group)
        text = "|".join(group)
        if arg := flag.get("arg"):
            text = f"{text} <{arg}>"
        if not required:
            text = f"[{text}]"
        rendered.append(text + "..." if flag.get("repeatable") else text)
    return rendered


def _render_usage(program: str, path: list[str], usage: dict) -> str:
    """A usage line, rebuilt from what the manifest records.

    The manifest records which tokens are required, not the order the help author
    typed them in, so the line is rebuilt in a canonical one: what you must pass
    before what you may, positionals before flags within each. That happens to
    reproduce the source line for the usual shapes, and reads better than the
    source for the ones where it doesn't — a required `--path` renders ahead of
    an optional `[<dir>]` rather than behind it."""
    # `or []` throughout the renderer: a key present with no value is YAML's
    # null, which means the same as the key being absent. The generator never
    # writes one, but the committed manifest it reads back has been through a
    # human's editor and a merge.
    args = usage.get("args") or []
    flags = usage.get("flags") or []
    return " ".join([
        program, *path,
        *[_render_arg(a) for a in args if not a.get("optional")],
        *_render_flags(flags, required=True),
        *[_render_arg(a) for a in args if a.get("optional")],
        *_render_flags(flags, required=False),
    ])


def _render_command(program: str, command: dict, path: list[str], out: list[str]) -> None:
    here = [*path, command["name"]]
    for usage in command.get("usages") or []:
        out.append(_render_usage(program, here, usage))
        if summary := usage.get("summary"):
            out.append(f"    {summary}")
    for sub in command.get("subcommands") or []:
        _render_command(program, sub, here, out)


def render_markdown(manifest: dict, source: str) -> str:
    """The manifest as a command reference page. `source` names the manifest the
    page was rendered from, so a reader who spots something wrong knows the page
    is a projection and where the truth lives."""
    program = manifest["name"]
    lines = [f"# {program}", ""]
    if summary := manifest.get("summary"):
        lines += [summary, ""]
    lines += [
        f"<!-- Generated by shipyard from {source} — do not edit by hand. -->",
        "",
        f"The command and flag grammar `{program}` documents in its own help "
        "output. It records what the CLI documents, which is not necessarily "
        "everything it accepts.",
        "",
    ]
    for usage in manifest.get("usages") or []:
        lines += ["```text", _render_usage(program, [], usage), "```", ""]
    for command in manifest.get("commands") or []:
        forms: list[str] = []
        _render_command(program, command, [], forms)
        lines += [f"## `{program} {command['name']}`", "", "```text", *forms, "```", ""]
    return "\n".join(lines)


def docs_page(root: str | pathlib.Path | None = None) -> str | None:
    """The reference page for the committed manifest, or None when the repo
    declares no CLI. A declared manifest that hasn't been generated yet is not an
    error here — the page appears once `generate` has written it."""
    path = target(root)
    if path is None or not path.exists():
        return None
    manifest = yaml.safe_load(path.read_text()) or {}
    source = path.relative_to(plugin_root(root)).as_posix()
    if not manifest.get("name"):
        # build-docs gates the release, so an unreadable manifest has to name
        # itself here rather than reaching the renderer and surfacing as a
        # KeyError from inside the docs build.
        raise SystemExit(
            f"shipyard: {source} carries no `name`, so it isn't a CLI manifest. "
            "Re-record it with `shipyard gen-cli-manifest`.")
    return render_markdown(manifest, source)
