"""Project the rostered plugins' plugin.yml `suite:` blocks → docs/plugins.js.

The aggregator's doc site reads a `PLUGINS` object keyed by plugin name; the
`suite:` block's keys mirror that object, so the projection is a direct YAML→JSON
dump. Two fields are merged in beyond the block:

  version     — authoritative in plugin.yml; the catalog card shows it as a badge.
  components  — the plugin's current named artifacts, replayed from the artifact
                log the roster declares. Derived, never declared, so the card's
                expander can't list a skill the plugin no longer ships.
  reference   — whether the plugin declares a `cli:`, which is what makes
                `build-docs` publish a command reference for it. The card sends
                its cli mark there, so a plugin without one must not be linked
                to a page that doesn't exist.

A `GROUPS` array rides alongside, carrying each catalog group's presentation in
display order. Membership is not in it: a card's group is its own `suite.group`
above, so the catalog derives the grouping from the plugins rather than from a
second list that can disagree with them.

docs/plugins.js is a render target — regenerated on every docs build, not committed.
"""
from __future__ import annotations

import json
import pathlib

from ._aggregate import components, groups, load_spokes
from ._common import plugin_root


def build(root: str | pathlib.Path | None = None) -> str:
    named = components(root)
    plugins = {}
    for name, spec in load_spokes(root).items():
        suite = spec.get("suite")
        if not suite:
            raise SystemExit(
                f"shipyard: {name}/plugin.yml has no suite: block — "
                "the catalog card is projected from it")
        entry = dict(suite)
        if "version" in spec:
            entry["version"] = str(spec["version"])
        if "cli" in spec:
            entry["reference"] = True
        if name in named:
            entry["components"] = named[name]
        plugins[name] = entry
    body = json.dumps(plugins, indent=2, ensure_ascii=False)
    catalog = json.dumps([{k: g[k] for k in ("key", "accent", "tag")}
                          for g in groups(root)], indent=2, ensure_ascii=False)
    return (
        "// Generated by shipyard gen-plugins-js — do not edit by hand.\n"
        "// Per-plugin content comes from each plugin's plugin.yml (suite: block);\n"
        "// the groups come from the aggregator's plugins.yml.\n"
        f"const PLUGINS = {body};\n"
        f"const GROUPS = {catalog};\n"
    )


def run(root: str | pathlib.Path | None = None) -> int:
    target = plugin_root(root) / "docs" / "plugins.js"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build(root))
    return 0
